name: Download Address

on: [push]

jobs:
  download_addr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v1
      - name: Set up
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install modules
        run: python -m pip install -r requirements.txt
      - name: Crawl
        run: python scr_addr.py
      - name: Deploy
        run: |
          git config user.name "personpiff"
          git config user.email "personpi@protonmail.com"
          git add .
          git commit -m "Crawled at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${GH_TOKEN}@github.com/personpiff/img-crawler.git" main:main
